"""Initial migration

Revision ID: c389a77a0549
Revises: 
Create Date: 2025-11-23 13:46:24.503335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c389a77a0549'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_records_id'), 'bank_records', ['id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('debit', sa.Float(), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_id'), 'bank_transactions', ['id'], unique=False)
    op.create_table('bank_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_uploads_id'), 'bank_uploads', ['id'], unique=False)
    op.create_index(op.f('ix_bank_uploads_upload_id'), 'bank_uploads', ['upload_id'], unique=False)
    op.create_table('erp_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('debit', sa.Float(), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_transactions_id'), 'erp_transactions', ['id'], unique=False)
    op.create_table('master_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_records_id'), 'master_records', ['id'], unique=False)
    op.create_table('reconciliation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_record_id', sa.Integer(), nullable=False),
    sa.Column('matched_master_id', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reconciled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_record_id'], ['bank_records.id'], ),
    sa.ForeignKeyConstraint(['matched_master_id'], ['master_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_results_id'), 'reconciliation_results', ['id'], unique=False)
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_reconciliation_results_id'), table_name='reconciliation_results')
    op.drop_table('reconciliation_results')
    op.drop_index(op.f('ix_master_records_id'), table_name='master_records')
    op.drop_table('master_records')
    op.drop_index(op.f('ix_erp_transactions_id'), table_name='erp_transactions')
    op.drop_table('erp_transactions')
    op.drop_index(op.f('ix_bank_uploads_upload_id'), table_name='bank_uploads')
    op.drop_index(op.f('ix_bank_uploads_id'), table_name='bank_uploads')
    op.drop_table('bank_uploads')
    op.drop_index(op.f('ix_bank_transactions_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_bank_records_id'), table_name='bank_records')
    op.drop_table('bank_records')
    # ### end Alembic commands ###
