"""Add status column to bank_records

Revision ID: d368febcc7aa
Revises: f98fba3aa714
Create Date: 2025-10-28 22:09:52.906090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd368febcc7aa'
down_revision: Union[str, Sequence[str], None] = 'f98fba3aa714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_records', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_records', 'status')
    # ### end Alembic commands ###
