"""Add status column to bank_records

Revision ID: f98fba3aa714
Revises: efff1cf2a9ac
Create Date: 2025-10-28 21:59:11.927501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98fba3aa714'
down_revision: Union[str, Sequence[str], None] = 'efff1cf2a9ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reconciliation_results_id'), 'reconciliation_results', ['id'], unique=False)
    op.drop_constraint(op.f('reconciliation_results_bank_record_id_fkey'), 'reconciliation_results', type_='foreignkey')
    op.create_foreign_key(None, 'reconciliation_results', 'bank_records', ['bank_record_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reconciliation_results', type_='foreignkey')
    op.create_foreign_key(op.f('reconciliation_results_bank_record_id_fkey'), 'reconciliation_results', 'bank_records', ['bank_record_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_reconciliation_results_id'), table_name='reconciliation_results')
    # ### end Alembic commands ###
