"""init schema

Revision ID: b99b0265036b
Revises: 
Create Date: 2025-09-28 16:19:24.568244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b99b0265036b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_type', sa.Enum('matched', 'unmatched_bank', 'unmatched_erp', name='resulttype'), nullable=False),
    sa.Column('bank_reference', sa.String(), nullable=True),
    sa.Column('erp_reference', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_results_id'), 'reconciliation_results', ['id'], unique=False)
    op.alter_column('bank_transactions', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bank_transactions', 'debit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('bank_transactions', 'credit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('bank_transactions', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('ix_bank_transactions_transaction_id'), table_name='bank_transactions')
    op.alter_column('erp_transactions', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('erp_transactions', 'debit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('erp_transactions', 'credit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('erp_transactions', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('ix_erp_transactions_transaction_id'), table_name='erp_transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_erp_transactions_transaction_id'), 'erp_transactions', ['transaction_id'], unique=False)
    op.alter_column('erp_transactions', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('erp_transactions', 'credit',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('erp_transactions', 'debit',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('erp_transactions', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_bank_transactions_transaction_id'), 'bank_transactions', ['transaction_id'], unique=False)
    op.alter_column('bank_transactions', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('bank_transactions', 'credit',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('bank_transactions', 'debit',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('bank_transactions', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_reconciliation_results_id'), table_name='reconciliation_results')
    op.drop_table('reconciliation_results')
    # ### end Alembic commands ###
